{
  self,
  inputs,
  ...
}:
{
  flake.nixosModules.astraConfig =

    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:
    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ "dm-snapshot" ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/mapper/vgastra-rootfs";
        fsType = "ext4";
        options = [
          "exec" # Allows execution of files
        ];
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/9F1B-213C";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      fileSystems."/home" = {
        device = "/dev/mapper/vgastra-homefs";
        fsType = "ext4";
        options = [
          "users" # Allows any user to mount/unmount
          "exec" # Allows execution of files
        ];
      };

      fileSystems."/extra" = {
        device = "/dev/mapper/vgastra-extrafs";
        fsType = "ext4";
        options = [
          "users" # Allows any user to mount/unmount
          "nofail" # Allows system to continue to boot if drive cannot be mounted
          "exec" # Allows execution of files
        ];
      };

      fileSystems."/extrados" = {
        device = "/dev/mapper/vgmilky-extradosfs";
        fsType = "ext4";
        options = [
          "users" # Allows any user to mount/unmount
          "nofail" # Allows system to continue to boot if drive cannot be mounted
          "exec" # Allows execution of files
        ];
      };

      swapDevices = [
        { device = "/dev/mapper/vgastra-swap"; }
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
