{
  self,
  inputs,
  ...
}:
{
  flake.nixosModules.jupiterConfig =
    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:
    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ "dm-snapshot" ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.kernelParams = [
        "amd_iommu=on"
        "iommu=pt"
      ];
      boot.extraModulePackages = [ ];

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/6FCD-71A1";
        fsType = "vfat";
        options = [
          "fmask=0022"
          "dmask=0022"
        ];
      };

      fileSystems."/" = {
        device = "/dev/vgjupiter/rootfs";
        fsType = "ext4";
        options = [
          "exec" # Allows execution of files
        ];
      };
      fileSystems."/home" = {
        device = "/dev/vgjupiter/homefs";
        fsType = "ext4";
        options = [
          "users" # Allows any user to mount/unmount
          "exec" # Allows execution of files
        ];
      };

      fileSystems."/vm" = {
        device = "/dev/mapper/vgjupiter-vmfs";
        fsType = "ext4";
        options = [
          "users" # Allows any user to mount/unmount
          "nofail" # Allows system to continue to boot if drive cannot be mounted
          "exec" # Allows execution of files
        ];
      };

      swapDevices = [
        { device = "/dev/vgjupiter/swap"; }
      ];

      # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
      # (the default) this is the recommended approach. When using systemd-networkd it's
      # still possible to use this option, but it's recommended to use it in conjunction
      # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
      networking.useDHCP = lib.mkDefault true;
      # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
