{
  self,
  inputs,
  ...
}:
{
  flake.nixosModules.stitanConfig =
    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:
    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "xhci_pci"
        "ehci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ "dm-snapshot" ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.kernelParams = [
        "intel_iommu=on"
        "iommu=pt"
      ];
      boot.extraModulePackages = [ ];

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/D284-08FE";
        fsType = "vfat";
        options = [
          "fmask=0022"
          "dmask=0022"
        ];
      };

      fileSystems."/" = {
        device = "/dev/vgstitan/rootfs";
        fsType = "ext4";
      };

      fileSystems."/home" = {
        device = "/dev/vgstitan/homefs";
        fsType = "ext4";
      };

      fileSystems."/vm" = {
        device = "/dev/vgstitan/vmfs";
        fsType = "ext4";
      };

      swapDevices = [
        { device = "/dev/vgstitan/swap"; }
      ];

      # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
      # (the default) this is the recommended approach. When using systemd-networkd it's
      # still possible to use this option, but it's recommended to use it in conjunction
      # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
      networking.useDHCP = lib.mkDefault true;
      # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
